# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: 'Build Java App'
  jobs:
  - job: Build
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: CopyFiles@2
      inputs:
        Contents: '**/*.war'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'warfile'
        publishLocation: 'Container'

- stage: DeployToTest
  displayName: 'Deploy to Test Environment'
  dependsOn: Build
  jobs:
  - job: DeployTest
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        artifactName: 'warfile'
        downloadPath: '$(Build.ArtifactStagingDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(1)(0f83a888-0468-4dd8-9412-f949e6222974)'
        appType: 'webAppLinux'
        WebAppName: 'rahylshettyacademy'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.war'

- stage: RunTests
  displayName: 'Run Automated Tests'
  dependsOn: DeployToTest
  jobs:
  - job: RunTests
    steps:
    - script: |
        echo "Cloning test repository..."
        git clone https://github.com/theta1211/UdemyAutomation.git
      displayName: 'Clone Test Repository'

    - script: |
        mvn test
      displayName: 'Run Tests'

- stage: ProductionDeployment
  displayName: 'Deploy to Prod Environment'
  dependsOn: RunTests
  jobs:
    - job: deploy
      steps:
        - task: AzureRmWebAppDeployment@5
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Azure subscription 1(4)(0f83a888-0468-4dd8-9412-f949e6222974)'
            appType: 'webAppLinux'
            WebAppName: 'prodrahulshettyacademyatudemy'
            packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.war'
            DeploymentTypeLinux: 'oneDeploy'